apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitdata
  name: gitdata-rust
  labels:
    apptype: gitdata-rust
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: gitdata-rust
  template:
    metadata:
      labels:
        app: gitdata-rust
        apptype: gitdata-rust
    spec:
      containers:
        - name: gitdata-rust
          image: gitdatateam/gitdatarust:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
