apiVersion: v1
kind: Service
metadata:
  name: gitdata-ui-service
  namespace: gitdata
  labels:
    apptype: gitdata-ui
spec:
  type: ClusterIP
  selector:
    app: gitdata-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80