apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-jzhub-com-certificate
spec:
  secretName: cloud-jzhub-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - jzhub.gitdata.com
