name: Check Pr

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build Frontend
    runs-on: [ self-hosted ]
    outputs:
      version: "${{ steps.version.outputs.version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Event
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Action: ${{ github.action }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Head Repository: ${{ github.head_repository }}"
          echo "Base Repository: ${{ github.base_repository }}"

      - name: Get version
        id: version
        run: |
          if [[ -n "$GITHUB_REF" && "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "tag version"
            echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
          else
            echo "commit version"
            echo "::set-output name=version::${{ github.sha }}"
          fi

      - name: Build and Push GitDataWeb
        run: |
          docker build -t gitdatateam/gitdataweb:${{ steps.version.outputs.version }} .
          docker rmi $(docker images -f "dangling=true" -q)

